all:
  children:
    gpu_nodes:
      hosts:
        gpu_node_1:
          ansible_host: 89.169.98.61
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../id_nebius
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
        gpu_node_2:
          ansible_host: 89.169.109.0
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../id_nebius
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
      vars:
        ansible_python_interpreter: /usr/bin/python3
